@prefix = {{host}}/api/auth

### create:success
@username = {{$random.alphabetic()}}
POST {{prefix}}/create
content-type: application/json

{
  "username": "用户{{username.substr(0, 5)}}",
  "email": "{{username}}@gmail.com",
  "password": "123123"
}
### login:success
POST {{prefix}}/login
content-type: application/json

{
  "email": "jkHrtiaakh@gmail.com",
  "password": "123123"
}

### code:success
GET {{prefix}}/code?width=200&height=300&type=login
content-type: application/json