@prefix = {{host}}/api/auth

### create:success
@realName = {{$random.alphabetic()}}
POST {{prefix}}/create
content-type: application/json

{
  "realName": "用户{{realName.substr(0, 5)}}",
  "email": "{{realName}}@gmail.com",
  "password": "a123123."
}
### login:success
POST {{prefix}}/login
content-type: application/json

{
  "email": "jkHrtiaakh@gmail.com",
  "password": "a123123."
}

### code:success
GET {{prefix}}/code?width=200&height=300&type=login
content-type: application/json