@prefix = {{host}}/api

### getAllUser
GET {{prefix}}/user/list
  ?offset=0&limit=20

### getUserById
GET {{prefix}}/user/1

### createUser
@username = {{$random.alphabetic(10)}}
POST {{prefix}}/user/create
content-type: application/json

{
    "name": "{{username}}",
    "age": {{$randomInt 5 150}}
}
