@prefix = {{host}}/api/user

### getAllUser
GET {{prefix}}/list
  ?offset=0&limit=20

### getUserById
GET {{prefix}}/4

### createUser
@username = {{$random.alphabetic(10)}}
POST {{prefix}}/create
content-type: application/json

{
    "name": "{{username}}",
    "age": {{$randomInt 5 150}}
}
