@prefix = http://localhost:3333/api
{{
  exports.defaultHeaders = {
    'Content-Type': 'application/json'
  };
}}

### getDemo
GET {{prefix}}/demo/1
Accept-Version: drizzle:sqlite

### getDemos
GET {{prefix}}/demo
  ?page=0&per_page=10
Accept-Version: drizzle:sqlite


### createDemo
@name = {{$random.alphabetic(10)}}
POST {{prefix}}/demo
Content-Type: application/json
Accept-Version: drizzle:sqlite
{
  "name": "before-{{name}}"
}

### updateDemo
@name = {{$random.alphabetic(10)}}
PATCH {{prefix}}/demo/1
Content-Type: application/json
Accept-Version: drizzle:sqlite
{
  "name": "after-{{name}}"
}


### deleteDemo
DELETE {{prefix}}/demo/1
Accept-Version: drizzle:sqlite