@prefix = http://localhost:3333/api
{{
  exports.defaultHeaders = {
    'Content-Type': 'application/json'
  };
}}

### getDemo
GET {{prefix}}/demo/1
Accept-Version: typeorm:mysql

### getDemos
GET {{prefix}}/demo
  ?page=0&perPage=10
Accept-Version: typeorm:mysql


### createDemo
@name = {{$random.alphabetic(10)}}
POST {{prefix}}/demo
Content-Type: application/json
Accept-Version: typeorm:mysql
{
  "name": "before-{{name}}"
}

### updateDemo
@name = {{$random.alphabetic(10)}}
PATCH {{prefix}}/demo/1
Content-Type: application/json
Accept-Version: typeorm:mysql
{
  "name": "after-{{name}}"
}


### deleteDemo
DELETE {{prefix}}/demo/1
Accept-Version: typeorm:mysql